### PR TITLE
Display card names in bold

### PR DESCRIPTION
**Pull request by tooomm**
Further improvements to text-only mode.
Partially addresses #752

I couldn't make the alternative text for images, which contains the name too, work yet.

names

### CODE REVIEW

**Comment by tooomm** [comment]
@HerveH44 can you help me with making the alternative text for images bold, too?

**Comment by HerveH44** [comment]
I don't know if that's possible. maybe read that : https://stackoverflow.com/questions/7101743/can-i-style-an-images-alt-text-with-css

It seems possible if you add maybe the css property "font-weight": bolder on the "img" inside the span?

**Comment by tooomm** [comment]
Nothing I can deal with right now.
Will add that to the issue.

**Comment by tooomm** [comment]
This is ready for merge by the way.

**Pull request merged**
