### PR TITLE
Fix grn guildgates

### PR DESCRIPTION
**Pull request by HerveH44**
Fix the guildgates names, removing the (a) and (b) from their names

### CODE REVIEW

**Comment by tooomm** [comment]
Isn't that fixed at mtgjson site already? @ZeldaZach

**Comment by ZeldaZach** [comment]
V4, yes. V3, nope.

**Comment by tooomm** [comment]
Looking into using v4 instead makes more sense then I guess?
Is there a current output available somewhere @ZeldaZach?

**Comment by HerveH44** [comment]
@ZeldaZach V4, as outputed elsewhere (don't remember if it was on gitter), still lacks "booster" parameter on sets, and still doesn't show "multiverseId" of cards. 
I can't use v4 unless this is fixed :( !

**Comment by ZeldaZach** [comment]
`multiverseId` was added back, but booster is missing... We need to come up with a better solution / way to impl it. Feel free to help chime in

**Comment by ZeldaZach** [comment]
It should be there... it’s on my build. Are you sure you’re up to date with master

**Comment by HerveH44** [comment]
Well after a quick check, there's indeed a "multiverseId" in v4 ... but v3 wrote it "multiverserid"

**Comment by HerveH44** [comment]
So, we need to do a special PR to update dr4ft to v4.

**Pull request merged**
