### PR TITLE
add cubecobra integration

### LINKED ISSUE #875: Cube Cobra integration
Cube draft feature request:
Add the ability to input a Cube ID to import from https://cubecobra.com/.

### PR DESCRIPTION
**Pull request by HerveH44**
closes #875

### CODE REVIEW

**Comment by ZeldaZach** [comment]
With this PR, I'd like to drop support for the "Preset" cubes, as this will take the burden of updating off our backs. We should just have the list and the CubeCobra importer.

**Comment by HerveH44** [comment]
it makes sense. Thinking about it, @dekkerglen do you have an API that retrieves the top X lists used or trending lists?

**Comment by dekkerglen** [comment]
We don't - I do hear that the Dekkaru cube is pretty hot right now though: https://cubecobra.com/cube/list/dekkaru

**Comment by HerveH44** [comment]
You have a page for "most drafted cubes" or "featured cubes", could I fetch some informations about them? That would be a nice integration

**Comment by dekkerglen** [comment]
Created an issue for it: https://github.com/dekkerglen/CubeCobra/issues/1308

**Comment by tooomm** [comment]
I also think preset cubes are no longer needed.

But it took me a while to figure out what an CubeCobra's "CubeID" is as it's not explained on our side and on his page there is also no hint where to grab it. One need to know that it's the last part of the URL...
Maybe you want to show that on your page more prominent as part of every cubes details page? @dekkerglen

**Comment by dekkerglen** [comment]
Cube IDs are manually set by users in the cube overview tab. It makes sense that cube owners know their ID, but it is not friendly toward people unfamiliar with the site. 

Created this issue: https://github.com/dekkerglen/CubeCobra/issues/1314

**Pull request merged**
