### PR TITLE
fix settings radio buttons, add scss support

### PR DESCRIPTION
**Pull request by mixmix**
## Linked tickets
- Fixes https://github.com/dr4fters/dr4ft/issues/1155

## Explanation of the issue

Settings radios were not visible

## Description of your changes

- change settings to be highlighted buttons
- add scss support
     - made making this change easier
     - should make future design changes better scoped, easier to maintain

## Screenshots

image

### CODE REVIEW

**Comment by mixmix** [comment]
I am well aware that I fixed a bug AND added a feature (scss) support.
I chose to do this because the current styling support (css) is monolithic and hard to engage with - basically because CSS gets really out of control if you don't pin it down clearly, as you can have styles having wild unintended side effects across the app.

What I've added will make it more likely for me (and devs like me) to engage with improving the UI

If people don't like scss, they can still write css, but this allows them to at least add it in a file associated with the component

**Comment by tooomm** [comment]
Thanks for the fix and opening a PR right away @mixmix!

However, I can't check this. Hope @ZeldaZach gets to it.

<br>

Your solution to use buttons over the initial radio buttons is fine and a big improvement over the current broken styling! Thanks for providing a screenshot as our Heroku Review App didn't trigger to build a live version of the change.

May I ask why you chose to not align the buttons more to the right?

**Comment by mixmix** [comment]
Thanks for having a look @tooomm

Re buttons being right aligned, I'm not 100% sure what you mean? I went for indented and left aligned because that seemed tū be the pattern followed elsewhere. If you want to clarify what you mean with a sketch happy to adjust.

Also if you'd like to see what this looks liked in practice happy to deploy this to an instance I'm running

**Comment by mixmix** [comment]
I see i gun you meant why did I indent? Yeah given these are not sub options like elsewhere I think the indent of be removed. I'll change that

**Comment by tooomm** [comment]
Haha, yeah... I got confused myself. Of course I meant left aligned.
I asked because it looks like it doesn't align with anything else currently regarding your screen:
indent

I'm not saying I dislike it per se, but then the card langauge selector needs the same adjustments at least?
Anyway, the gap feels kinda big. Maybe you can test both and see what looks and feels nicer for the panel overall.

Thanks for the kind offer to link to your instance. But here the screen is good enough for me I think. :)

**Comment by mixmix** [comment]
image

yeah that looks better (cc @tooomm )

**Review by ZeldaZach — APPROVED** [review]
I'm very happy with this change! Thank you so much for your support of our project :)

**Comment by tooomm** [comment]
Thanks for having a second look! @mixmix

**Comment by mixmix** [comment]
I hope this is the first of many bits of support I can offer!
Thanks for the reviews and fast merge <3

**Pull request merged**
