### PR TITLE
README: update known sites

### PR DESCRIPTION
**Pull request by tooomm**
remove dr4ft.com
~~add trsbox~~

### CODE REVIEW

**Comment by tooomm** [comment]
Same for me now, maybe they are updating...
I remember that side back from the old times of drafter, and it looks like @trsbox is hosting the new version now too! ❤️

**Comment by HerveH44** [comment]
Well if there's not any other site running dr4ft code, then we could take some time to do the #99 refactor as we can break compatibility with previous configuration setups !

**Comment by ZeldaZach** [comment]
I’m fine with this

**Comment by tooomm** [comment]
I tried several times now in between without luck.

I removed it again.

**Pull request merged**
