### PR TITLE
allow semver minor upgrades, bump fuse.js major

### PR DESCRIPTION
**Pull request by mixmix**
I noticed many of the modules have been locked to exact version numbers.
This is an experiment in allowing them all to have minor semver upgrades (`^x.x.x`)

Spinning up the server seems to work fine. Will need to smoke test this a little more to make sure it's safe

---

used this script to bump versions in package.json
```bash
$ npx npm-check-updates --target minor -u
```

### CODE REVIEW

**Comment by mixmix** [comment]
This leaves a few major upgrades: 

```
mixmix projects/dr4ft ‹semver_minors› » npm outdated                                                            1 ↵
Package              Current  Wanted  Latest  Location                          Depended by
copy-webpack-plugin    6.4.1   6.4.1   8.0.0  node_modules/copy-webpack-plugin  dr4ft
css-loader             3.6.0   3.6.0   5.1.1  node_modules/css-loader           dr4ft
engine.io              3.5.0   3.5.0   5.0.0  node_modules/engine.io            dr4ft
engine.io-client       3.5.1   3.5.1   5.0.0  node_modules/engine.io-client     dr4ft
helmet                3.23.3  3.23.3   4.4.1  node_modules/helmet               dr4ft
html-webpack-plugin    4.5.2   4.5.2   5.3.1  node_modules/html-webpack-plugin  dr4ft
node-sass             4.14.1  4.14.1   5.0.0  node_modules/node-sass            dr4ft
sass-loader           10.1.1  10.1.1  11.0.1  node_modules/sass-loader          dr4ft
style-loader           1.3.0   1.3.0   2.0.0  node_modules/style-loader         dr4ft
webpack               4.46.0  4.46.0  5.24.4  node_modules/webpack              dr4ft
webpack-cli           3.3.12  3.3.12   4.5.0  node_modules/webpack-cli          dr4ft
webpack-merge          4.2.2   4.2.2   5.7.3  node_modules/webpack-merge        dr4ft

```

**Comment by tooomm** [comment]
I see the Heroku deployment failing in the last PR's. Any idea which recent change could cause this @mixmix?

Otherwise we need Herve to look into the logs.

**Comment by mixmix** [comment]
No idea. Oh I have been using node 14 whereas this project says it should be node 12. Don't know if that should cause any problems with lockfile

@HerveH44 can you see what's up?
Also can you make it so I / others can see that log in future?

**Comment by tooomm** [comment]
https://beta-dr4ft.herokuapp.com/, which used to auto deployed from the master branch, is also not working correctly anymore.

It showed the new set selection drop downs when I tried it, but there were no set names shown. Only the set icons.
When I clicked on it, the site somehow hang. Then, the old drop downs with no search and no icons showed up on my next try.

**Comment by mixmix** [comment]
I've seen the app hang with that drop down being clicked too, but reinstalling node modules seems to fix it. I've also upgraded the module I think is causing the hang in another branch (not sure why though)

**Comment by tooomm** [comment]
Hmm, interesting. We should keep watching out for that.

>Oh I have been using node 14 whereas this project says it should be node 12. Don't know if that should cause any problems with lockfile

Me neither. The CI runs completly fine on both, v12.21.0 and v14.16.0.

**Comment by mixmix** [comment]
merged

**Pull request closed without merging**
