### PR TITLE
improve loading hint

### LINKED ISSUE #104: loading hint improvements
While https://github.com/dr4fters/dr4ft/commit/394ad998a81a929f7b3656eb90ddb40678560517 added a little loading info, that doesn't help too much.

A user with script blocking enabled will still wonder why it's not loading. :)
loading

I thought more of something like this:
javascript hint

While that might be a complex and overkill solution, a more informative and prettier banner in the middle of the page would be a big improvement.

What about something like this?
loading-new

### PR DESCRIPTION
**Pull request by tooomm**
Fixes #104

Before:
before

After:
after

### CODE REVIEW

**Comment by HerveH44** [comment]
Seems fine !

**Comment by tooomm** [comment]
Any idea how to center it and give it a border as in my mockup in https://github.com/dr4fters/dr4ft/issues/104?

Or do you have any other idea to style, highlight or better place it @HerveH44?

**Comment by tooomm** [comment]
@HerveH44 Do you have some input on how to better style it or implement something along the lines like my mockup?

Otherwise I would merge as is and leave the styling for somebody else.

**Comment by HerveH44** [comment]
@tooomm , I pushed some changes, it looks a bit more like what you showed in the mock. CSS is not my top language, tell me if you like it

**Comment by tooomm** [comment]
I restyled it a bit. Thanks for the initial work @HerveH44, that allowed me to play around! 👍 

The problems I'm still experiencing is that I can't use the svg icon instead the bad quality png...
https://github.com/dr4fters/dr4ft/blob/21dbc58d47b3e6c41c4676e584bdc1135f7ab848/public/4.svg

**Comment by ZeldaZach** [comment]
Your SVG is blank... that's probably the reason :P

**Comment by tooomm** [comment]
Hmm, Inkscape shows it for me... have to check the file.
Any idea what's up with the file you gave me once @dev-id?

**Comment by tooomm** [comment]
No idea what's up with the svg. I can correctly load it with Inkscape and I created all png's off of it for https://github.com/dr4fters/dr4ft/pull/115

Removed it for now, we can still exchange the logo at a later point!

**Comment by tooomm** [comment]
@HerveH44 can you please take a second look here after the changes?
I used our png for now due to the problems with the svg. Will address that in a later PR.

**Comment by tooomm** [comment]
No worries. Everything was a bit stale around here. 😉

**Pull request merged**
