### PR TITLE
add additional favicons + fix viewport scale on phones

### PR DESCRIPTION
**Pull request by Noojuno**
**Changes for #1465**
Adds icons of additional sizes for mobile and hd browser icons. This could use testing on iOS and Mac devices as I only have an android phone and windows pc. 

Firefox top sites: 
kicxAPS

**Adds meta tag for viewport sizing**
The site was cut off on smaller screens, so I added the `viewport` meta tag to stop it from cutting off.

Before: 
znpNJzF

After:
oYlqcKQ

### CODE REVIEW

**Comment by mixmix** [comment]
This is sweet.
If anyone has a mac to test this on sing out (otherwise I'll see if I can nab a friends)

**Comment by mixmix** [comment]
I've spun this up and looked at it in chrome + firefox on linux. Looks good there

**Comment by tooomm** [comment]
As we can not request a Heroku build for this... if @mixmix deploys it to his domain we can use the linked page in my issue (https://realfavicongenerator.net/) and see what it reports back. It runs various checks.

**Comment by mixmix** [comment]
Merged-squashed into master.
Thanks @Noojuno !

**Pull request closed without merging**
