### PR TITLE
fix link display

### PR DESCRIPTION
**Pull request by tooomm**
removed unwanted space
untitled

### CODE REVIEW

**Comment by tooomm** [comment]
I think the best/prettiest solution would be:

[(GH) dr4fters/dr4ft](https://github.com/dr4fters/dr4ft) with `(GH)` beeing the GitHub icon

**Comment by HerveH44** [comment]
Hi @tooomm,

> I think the best/prettiest solution would be:
> (GH) dr4fters/dr4ft
> with (GH) beeing the GitHub icon

That's would be a really good idea. Do you think you could add the  tag? I guess the src would be https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png
or 
https://cdn1.iconfinder.com/data/icons/logotypes/32/github-256.png

**Comment by tooomm** [comment]
The png icons didn't look ideal.
I used a svg from here: https://www.flaticon.com/free-icon/github-logo_25231
We would need to check if it's *ok* to use.

I produced a mistakes here. Looks like the client.js config needs slightly adjusted html? @HerveH44

**Comment by HerveH44** [comment]
That's beautiful :) ! I love it. If @ZeldaZach is fine, let's merge it. 
Talking about merge, seen that it took several commits. Would it be ok to go for a "squash and merge" in order to get only one commit in the master branch?

**Comment by tooomm** [comment]
Thanks for fixing my mistake. 🙈 😄 

I love the heroku review app already!

**Comment by tooomm** [comment]
Any idea what went wrong here @HerveH44?

Looking at http://dr4ft.info/ I get this:
dr4ft-info

But the running version (https://github.com/dr4fters/dr4ft/commit/939068c) is the commit of the merge of this PR to master...

**Comment by HerveH44** [comment]
It was because we didn't rebundled the frontend. It's fixed.

**Pull request merged**
