### PR TITLE
Better look for cube list entry.

### PR DESCRIPTION
**Pull request by queercat**
Just looks better than a single-line textarea.

### CODE REVIEW

**Comment by tooomm** [comment]
Did you test this, @ZeldaZach ?

Looking at the Heroku deployment it seems to breaks somehow:
https://github.com/dr4fters/dr4ft/deployments

**Comment by ZeldaZach** [comment]
Looks fine on master. I deployed with no issues

**Comment by tooomm** [comment]
For me, selecting "cube" makes all site turn blank on the heroku deployment.

**Comment by tooomm** [comment]
@queercat Do you want to look further into this?
I also think displaying just one single card name of all list is not great. Unfortunately, your change made the site break...

**Pull request merged**
