### PR TITLE
Fix ESLint issues

### LINKED ISSUE #577: ESLint cleanup + fix
All travis builds throw a bunch of eslint errors since months.
https://travis-ci.com/dr4fters/dr4ft

Edit: It even errors completely and doesn't even run anymore.

### PR DESCRIPTION
**Pull request by t-moennich**
Resolves #577 

I had to add some plugins to get all things to work.
The amount of code changes are less then configuration or plugins but yeah - it's green :heavy_check_mark:

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Nice! Thanks for taking the time to help out. If you’d like to chat sometime, we’re on Discord (https://MTGJSON.com/discord)

**Comment by ZeldaZach** [comment]
Seems this had an issue and broke the site. Had to pull back. If you'd like to look into it, would be awesome

**Comment by tooomm** [comment]
@t-moennich Can you have a look again, please? We are stuck and can’t update the server with other changes.
Any idea why Zach is having issues with the server?

**Comment by t-moennich** [comment]
> @t-moennich Can you have a look again, please? We are stuck and can’t update the server with other changes.
> Any idea why Zach is having issues with the server?

Thats indeed strange - I'll take a look into it in the next few days.
Sorry for having trouble with it. I only ran some small smoketests locally

**Comment by tooomm** [comment]
> 
> 
> Seems this had an issue and broke the site. Had to pull back. If you'd like to look into it, would be awesome

@ZeldaZach Is that still an issue?
As the site claims to be running a commit from yesterday?
Did you manually remove this pr from the code you're currently hosting?

**Comment by ZeldaZach** [comment]
Happens. Just looking to get us brought back up to date :)

**Comment by ZeldaZach** [comment]
cc: @HerveH44

**Comment by HerveH44** [comment]
@ZeldaZach what exactly happened? What can I do to fix this?

**Comment by tooomm** [comment]
@t-moennich the issue seems to be solved somehow and Zach could build and host a new version of the site.

**Pull request merged**
