### PR TITLE
First draft at modal

### PR DESCRIPTION
**Pull request by crookedneighbor**
## Explanation of the issue

Converts create form to a modal dialog.

## Screenshots

draft

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I don't typically work in React, so I'm sure I'm doing some stuff that isn't the normal pattern for how it's done in React.

Make any changes you see fit.

**Comment by ZeldaZach** [comment]
Overall, I'm super ecstatic for this change! Great job, and thanks for helping bring dr4ft to the next level.

Only two real notes I have for you: I see the overlay popup is in dark mode. Are we going to be dark-mode only in the future? Is there a way we can get a toggle on Dr4ft to manage the color of the popup?

Also, if you put any invalid cards, red error text appears behind the popup as well as ontop of it. Probably an old fragment you forgot to delete.
Screenshot 2020-07-12 16 00 19

**Comment by crookedneighbor** [comment]
> I see the overlay popup is in dark mode.

That's all I was given in the design file.

> Also, if you put any invalid cards, red error text appears behind the popup as well as ontop of it. Probably an old fragment you forgot to delete.

This is because that error is exposed at the app level, so it encompasses any API error. To truly fix that, you'd need to completely rework how the create event happens... and I'm not willing to do that refactor for this bit.

**Comment by justinvoorhees** [comment]
### **Light mode color palette update**


color-palette

Link to the Sketch file: https://www.dropbox.com/s/xkloyzzbgiti218/dr4ft-wireframe_15.sketch?dl=0

**Comment by crookedneighbor** [comment]
draft

**Comment by justinvoorhees** [comment]
Very happy to see this merged and in action. Here's my feedback on some of the visuals:

I think the most impactful edit would be simply adjusting the .modal-container to max-width: 70%.

.modal-header <h2> is inheriting a margin-block-start/end rule from div.modal-container that gives the appearance of excessive padding-top/bottom when compared to .modal-footer.

The margin-bottom rule for the .modal-section-content <fieldset> is doubling up with the .modal-section’s padding-bottom, this also appears as excessive padding-bottom.

The .modal-section <label>’s display cursor:pointer, while the .modal-section <select> inputs are displaying cursor:none. This probably was intended to be the other way ‘round.

I acknowledge the use of em/rem but for fluency I feel the text visual hierarchy could condense down to something more like <h2> font-size: 22px / <label> font-size: 18px, font-weight: medium/500.

The input fields were intended to have a background-color: #FAFBFC and box-shadow: 0px 1px #F1F2F3.

The tooltip text would look better in white.

**Comment by justinvoorhees** [comment]
Very happy to see this merged and in action. Here's my feedback on some of the visuals:

I think the most impactful edit would be simply adjusting the max-width of the .modal-container to 70%.

.modal-header `<h2>` is inheriting a margin-block-start/end rule from div.modal-container that gives the appearance of excessive padding-top/bottom when compared to .modal-footer.

The margin-bottom rule for the .modal-section-content `<fieldset>` is doubling up with the .modal-section’s padding-bottom, this also appears as excessive padding-bottom.

The .modal-section `<label>`’s display cursor:pointer, while the .modal-section `<select>` inputs are displaying cursor:none. This probably was intended to be the other way ‘round.


I acknowledge the use of em/rem but for fluency I feel the text visual hierarchy could condense down to something more like `<h2>` font-size: 22px / `<label>` font-size: 18px, font-weight: medium/500.

The input fields were intended to have a background-color: #FAFBFC and box-shadow: 0px 1px #F1F2F3.

The tooltip text would look better in white.

**Comment by tooomm** [comment]
For reference only, the old page design and create options without the modal looked like this:
dr4ft - old create design - draft regular
dr4ft - old create design - draft cube
dr4ft - old create design - draft chaos
dr4ft - old create design - draft decadent
dr4ft - old create design - sealed regular
dr4ft - old create design - sealed cube
dr4ft - old create design - sealed chaos

**Pull request merged**
