### PR TITLE
Export again!

### PR DESCRIPTION
**Pull request by mixmix**
fixes https://github.com/dr4fters/dr4ft/issues/1454:
- changed mtgo export to just use `.txt` files

fixes https://github.com/dr4fters/dr4ft/issues/1242:
- added tests around "meld" layout cards

### CODE REVIEW

**Comment by tooomm** [comment]
@LotusWalker Can you please test this and let us know if it works now?

Check it here: https://beta-dr4ft-export-again-flwgcb.herokuapp.com/

**Comment by tooomm** [comment]
With commenting out the other mtgo .dek stuff, do you want to keep this?
https://github.com/dr4fters/dr4ft/blob/master/backend/import/toBoosterCard.js#L53

**Comment by mixmix** [comment]
Good point @tooomm yes I think this change sound be reverted. 

Do you think I should comment it out so people can see where you can get mtgoId, or straight up delete it?

**Comment by tooomm** [comment]
Go for whatever you feel preserves the best overview.

Extending the main .dek comment in `mtgo.js` is also an option?

**Comment by LotusWalker** [comment]
@mixmix Ran two drafts to test this and have some feedback. Thanks again for your great work on this!

1) Several cards didn't import into mtgo because their back side was on the TXT file, not their front side. These cards below did not import because of this:

Archangel Avacyn was listed as Avacyn, the Purifier
Jace, Vryn's Prodigy was listed as Jace, Telepath Unbound
Kytheon, Hero of Akros was listed as Gideon, Battle-Forged
Shatterskull Smashing was listed as Shatterskull, the Hammer Pass
Turntimber Symbiosis was listed as Turntimber, Serpentine Wood

So, transform cards and MDFC cards are impacted by this I believe.

2) For the MTGO download, can you make it just .txt instead of .mtgo.txt? We like to rename the filenames before downloading them to streamline things.

Thanks!

**Comment by mixmix** [comment]
Yeah can change that extension for sure.
I changed the logic to use a field called faceName which might not be as reliable as manually mutating the name of cards.
Will have a go

Thank you again @LotusWalker for your specific feedback. It's really awesome having specific examples cards to add to the tests. Each time we add more cases it gets better.

Honestly I'm quite surprised how fiddly this has been. I specifically remember saying "oh, that will be quite easy"!

**Comment by LotusWalker** [comment]
No worries! Let me know if you want me to test again after you've worked on it some more. Seems like a pain in the ass to get this feature perfect.

**Comment by mixmix** [comment]
wow super annoying!
I've not been able to reproduce this bug in development env,
but have been able to see it deployed (https://beta-dr4ft-export-again-flwgcb.herokuapp.com/)

It seems intermitent? When I enter cards for a cube it seems to be fine, but if I run a draft from a set I see problems......I've made made it so that if you know where to hover we can access the raw json data the output is being built from, so hopefully that will help reveal the problem

**Comment by mixmix** [comment]
OK, got something - turns out `card.faceName` IS NOT RELIABLE. i.e. it's not "the name of the front of the card
Have removed reliance on it in the code.

@ZeldaZach can you feed that back to the mtgJSON team please?

specific example:
```js
    {
        "name": "Vastwood Fortification // Vastwood Thicket",
        "faceName": "Vastwood Thicket"    // <<< expected this to be "Vastwood Fortification" as that's the "front"
    }
```

**Comment by mixmix** [comment]
@LotusWalker see if this has fixed it some could you?

**Comment by LotusWalker** [comment]
@mixmix Works perfectly now, nice!

**Comment by mixmix** [comment]
Given this has been "smoke tested" in staffing, I'm going to go ahead and merge this.

We'll need to keep an eye on when @ZeldaZach deploys next before being able to using in production

**Comment by tooomm** [comment]
>    For the MTGO download, can you make it just .txt instead of .mtgo.txt? We like to rename the filenames before downloading them to streamline things.

@LotusWalker What was the exact issue there? You could still rename them, just that the file extension yielded some (important) additional information. You could still remove that later if you prefer? I'm not so sure that everybody has a workflow like your group.

The problem now is that users can download two types of `.txt` files and an ordinary user can not tell which is designed for which use case once downloaded, which will lead to issues.

I can easily imagine a conversation like this:
A: My import is not working.
B: Did you use the .txt file?
A: Sure. (without noticing that he selected the wrong one)

Of course users should download the right one in the first place, but that will happen.

**Comment by mixmix** [comment]
I'm off same opinion as you @tooomm however, I'm also happy to wait to see how it goes for people. We can change it if we get confused feedback?

**Comment by LotusWalker** [comment]
@tooomm Yeah I see your point, but editing the file extensions would have just been one more annoying step for our group, and we all love it rn the way it is. Hopefully it’s pretty clear to folks which tab to use when downloading their decks, depending on what software they use to play matches.

**Comment by tooomm** [comment]
I've still a hard time following your argument in the first place @LotusWalker. 🙈 
Why would you even need (or want) to change the "extension" as you noted?
I did not think that useful (yet removable) tag could bother people.
Or is there some functional issue as all your group seemed to change it? That would be a different story.

**Pull request merged**
